### ISSUE TITLE
ImportError: cannot import name 'TextFoolerStrategy'

### ISSUE THREAD

**Issue by RachmadAgungP** [DAI-Lab/fibber#22] opened 2021-01-27 22:05 UTC
* fibber version: fibber 0.2.1 (google colab)
* Python version: 3.7
* Operating System: Windows

### Description

Error: cannot import name 'TextFoolerStrategy'

### What I Did

```
ImportError                               Traceback (most recent call last)
<ipython-input-5-9a0d82cb941d> in <module>()
----> 1 from fibber.fibber import Fibber
      2 
      3 
      4 wpe_weight = 1000  #@param {type:"raw"}
      5 wpe_threshold = 1. #@param {type:"raw"}

/usr/local/lib/python3.6/dist-packages/fibber/fibber.py in <module>()
      2 
      3 from fibber.metrics import MetricBundle
----> 4 from fibber.paraphrase_strategies import (
      5     BertSamplingStrategy, IdentityStrategy, RandomStrategy, TextFoolerStrategy)
      6 

ImportError: cannot import name 'TextFoolerStrategy'

```

**Comment by leix28** [comment] 2021-01-29 23:40
This import error is caused by recent refac to the code. TextFoolerStrategy is renamed as TextAttackStrategy.

This bug will be fixed in next release on Feb. 3.

**Comment by leix28** [comment] 2021-01-30 00:27
Currently, I added a workaround to the Colab notebook.

**Comment by leix28** [comment] 2021-02-05 20:36
Bug fixed.

**Closed by leix28** 2021-02-05 20:36 UTC
Labels: bug
