### ISSUE TITLE
AttributeError: 'MetricBundle' object has no attribute 'get_classifier_for_attack'

### ISSUE THREAD

**Issue by RachmadAgungP** [DAI-Lab/fibber#24] opened 2021-01-27 22:20 UTC
* fibber version: fibber 0.2.1 (google colab)
* Python version: 3.7
* Operating System: windows

### Description

AttributeError: 'MetricBundle' object has no attribute 'get_classifier_for_attack'

### What I Did

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-b1128aa16d94> in <module>()
      5 
      6 print("Original sentence:", input_sentence)
----> 7 pred = fibber.get_metric_bundle().get_classifier_for_attack().measure_example(None, input_sentence)
      8 print("Original sentence prediction:", pred)
      9 

AttributeError: 'MetricBundle' object has no attribute 'get_classifier_for_attack'
```

**Comment by leix28** [comment] 2021-01-30 00:25
This bug is caused by recent update to the code. The notebook is now fixed. 

If you run into any questions, please let me know.

**Comment by leix28** [comment] 2021-02-05 20:36
Bug fixed.

**Closed by leix28** 2021-02-05 20:36 UTC
Labels: bug
